apiVersion: v1
kind: Secret
metadata:
  name: lamp-k8s-secret
  namespace: lamp-k8s
type: Opaque
stringData:
  MYSQL_HOST: lamp-k8s-mysql
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: lamp_db
  MYSQL_USER: lamp_user
  MYSQL_PASSWORD: lamp_password
