apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lamp-k8s-ingress
  namespace: lamp-k8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lamp-k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lamp-k8s-apache
            port:
              number: 80
